=== Byte-fw/Byte/assets/config.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
    targetNamespace="https://www.w3schools.com" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="global">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:language" name="locale" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="core">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="inventory">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:byte" name="inventorySlots" />
                                        <xs:element type="xs:byte" name="maxPlayerWeight" />
                                        <xs:element name="items">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="item" maxOccurs="unbounded"
                                                        minOccurs="0">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element type="xs:string"
                                                                    name="name" />
                                                                <xs:element type="xs:string"
                                                                    name="label" />
                                                                <xs:element type="xs:string"
                                                                    name="description" />
                                                                <xs:element type="xs:byte"
                                                                    name="weight" />
                                                                <xs:element type="xs:boolean"
                                                                    name="unique" />
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Byte-fw/Byte/assets/config.xml
<config xmlns="https://www.w3schools.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.w3schools.com config.xsd">
    <global>
        <locale>en</locale>
    </global>
    <core>
        <inventory>
            <inventorySlots>20</inventorySlots>
            <maxPlayerWeight>100</maxPlayerWeight>
            <items>
                <item>
                    <name>weapon_pistol</name>
                    <label>Pistola</label>
                    <description>Pistola pium pium</description>
                    <weight>10</weight>
                    <unique>true</unique>
                </item>
                <item>
                    <name>tosti</name>
                    <label>Tostada</label>
                    <description>Tostada de pan</description>
                    <weight>1</weight>
                    <unique>false</unique>
                </item>
                <item>
                    <name>agua</name>
                    <label>Botella de agua</label>
                    <description>Botella de agua</description>
                    <weight>1</weight>
                    <unique>false</unique>
                </item>
                <item>
                    <name>cerveza</name>
                    <label>Cerveza</label>
                    <description>Cerveza</description>
                    <weight>1</weight>
                    <unique>false</unique>
                </item>
                <item>
                    <name>whisky</name>
                    <label>Whisky</label>
                    <description>Whisky</description>
                    <weight>1</weight>
                    <unique>false</unique>
                </item>
                <item>
                    <name>vodka</name>
                    <label>Vodka</label>
                    <description>Vodka</description>
                    <weight>1</weight>
                    <unique>false</unique>
                </item>
                <item>
                    <name>ron</name>
                    <label>Ron</label>
                    <description>Ron</description>
                    <weight>1</weight>
                    <unique>false</unique>
                </item>
                <item>
                    <name>tequila</name>
                    <label>Tequila</label>
                    <description>Tequila</description>
                    <weight>1</weight>
                    <unique>false</unique>
                </item>
                <item>
                    <name>gin</name>
                    <label>Gin</label>
                    <description>Gin</description>
                    <weight>1</weight>
                    <unique>false</unique>
                </item>
                <item>
                    <name>mojito</name>
                    <label>Mojito</label>
                    <description>Mojito</description>
                    <weight>1</weight>
                    <unique>false</unique>
                </item>
                <item>
                    <name>margarita</name>
                    <label>Margarita</label>
                    <description>Margarita</description>
                    <weight>1</weight>
                    <unique>false</unique>
                </item>
                <item>
                    <name>daiquiri</name>
                    <label>Daiquiri</label>
                    <description>Daiquiri</description>
                    <weight>1</weight>
                    <unique>false</unique>
                </item>
                <item>
                    <name>martini</name>
                    <label>Martini</label>
                    <description>Martini</description>
                    <weight>1</weight>
                    <unique>false</unique>
                </item>
                <item>
                    <name>bloodymary</name>
                    <label>Bloody Mary</label>
                    <description>Bloody Mary</description>
                    <weight>1</weight>
                    <unique>false</unique>
                </item>
            </items>
        </inventory>
    </core>
</config>
