=== Byte-fw/Byte/assets/events.xsd
<xs:schema
    attributeFormDefault="unqualified"
    elementFormDefault="qualified"
    targetNamespace="https://www.w3schools.com"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
    <xs:element name="events">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="eventName" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute type="xs:string" name="key" use="required" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Byte-fw/Byte/assets/events.xml
<events xmlns="https://www.w3schools.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.w3schools.com events.xsd">
    <eventName key="Shared.Debugger.BreakpointHit">Byte:shared:Debugger:BreakpointHit</eventName>
    <eventName key="Shared.Debugger.WatchpointHit">Byte:shared:Debugger:WatchpointHit</eventName>
    <eventName key="Shared.Debugger.BreakpointContinue">Byte:shared:Debugger:BreakpointContinue</eventName>

    <eventName key="Client.Player.SetPlayerField">Byte:client:Player:SetPlayerField</eventName>
    <eventName key="Client.Player.SetPlayerPedData">Byte:client:Player:SetPlayerPedData</eventName>
    <eventName key="Client.Player.OnPlayerReady">Byte:client:Player:OnPlayerReady</eventName>
    <eventName key="Client.Player.PlayerReadyData">Byte:client:Player:PlayerReadyData</eventName>

    <eventName key="Client.Inventory.SetInventory">Byte:client:Inventory:SetInventory</eventName>
    <eventName key="Client.RPC.Callback">Byte:client:RPC:Callback</eventName>
    <eventName key="Server.RPC.Call">Byte:server:RPC:Call</eventName>
</events>
